# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 30, 181, 411))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 115, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_track = QtWidgets.QPushButton(self.layoutWidget)
        self.button_track.setObjectName("button_track")
        self.verticalLayout.addWidget(self.button_track)
        self.button_scene = QtWidgets.QPushButton(self.layoutWidget)
        self.button_scene.setObjectName("button_scene")
        self.verticalLayout.addWidget(self.button_scene)
        self.button_ap = QtWidgets.QPushButton(self.layoutWidget)
        self.button_ap.setObjectName("button_ap")
        self.verticalLayout.addWidget(self.button_ap)
        self.button_rec = QtWidgets.QPushButton(self.layoutWidget)
        self.button_rec.setObjectName("button_rec")
        self.verticalLayout.addWidget(self.button_rec)
        self.button_interf = QtWidgets.QPushButton(self.layoutWidget)
        self.button_interf.setObjectName("button_interf")
        self.verticalLayout.addWidget(self.button_interf)
        self.button_import = QtWidgets.QPushButton(self.layoutWidget)
        self.button_import.setObjectName("button_import")
        self.verticalLayout.addWidget(self.button_import)
        self.button_run = QtWidgets.QPushButton(self.layoutWidget)
        self.button_run.setObjectName("button_run")
        self.verticalLayout.addWidget(self.button_run)
        self.mainGraph = GraphicsLayoutWidget(self.centralwidget)
        self.mainGraph.setGeometry(QtCore.QRect(210, 30, 521, 411))
        self.mainGraph.setObjectName("mainGraph")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 67, 17))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 28))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menusimulation = QtWidgets.QMenu(self.menubar)
        self.menusimulation.setObjectName("menusimulation")
        self.menuconfigure = QtWidgets.QMenu(self.menubar)
        self.menuconfigure.setObjectName("menuconfigure")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionrun = QtWidgets.QAction(MainWindow)
        self.actionrun.setObjectName("actionrun")
        self.actiongo = QtWidgets.QAction(MainWindow)
        self.actiongo.setObjectName("actiongo")
        self.actionstop = QtWidgets.QAction(MainWindow)
        self.actionstop.setObjectName("actionstop")
        self.actionpause = QtWidgets.QAction(MainWindow)
        self.actionpause.setObjectName("actionpause")
        self.actionAP = QtWidgets.QAction(MainWindow)
        self.actionAP.setObjectName("actionAP")
        self.menufile.addAction(self.actionopen)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionnew)
        self.menufile.addAction(self.actionsave)
        self.menufile.addAction(self.actionsave_as)
        self.menusimulation.addAction(self.actionrun)
        self.menusimulation.addSeparator()
        self.menusimulation.addAction(self.actiongo)
        self.menusimulation.addAction(self.actionstop)
        self.menusimulation.addAction(self.actionpause)
        self.menuconfigure.addAction(self.actionAP)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menusimulation.menuAction())
        self.menubar.addAction(self.menuconfigure.menuAction())
        self.label.setBuddy(self.button_track)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_track.setText(_translate("MainWindow", "轨道配置"))
        self.button_scene.setText(_translate("MainWindow", "场景选择"))
        self.button_ap.setText(_translate("MainWindow", "AP参数"))
        self.button_rec.setText(_translate("MainWindow", "接收机参数"))
        self.button_interf.setText(_translate("MainWindow", "干扰基站"))
        self.button_import.setText(_translate("MainWindow", "确认配置"))
        self.button_run.setText(_translate("MainWindow", "开始仿真"))
        self.label.setText(_translate("MainWindow", "参数设置"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menusimulation.setTitle(_translate("MainWindow", "simulation"))
        self.menuconfigure.setTitle(_translate("MainWindow", "configure"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave_as.setText(_translate("MainWindow", "save as ..."))
        self.actionrun.setText(_translate("MainWindow", "run"))
        self.actiongo.setText(_translate("MainWindow", "go"))
        self.actionstop.setText(_translate("MainWindow", "stop"))
        self.actionpause.setText(_translate("MainWindow", "pause"))
        self.actionAP.setText(_translate("MainWindow", "AP间隔"))


from pyqtgraph import GraphicsLayoutWidget
